version: 2.1

orbs:
  architect: giantswarm/architect@4.35.5

workflows:
  test:
    jobs:
      - architect/go-build:
          name: go-build-standup
          binary: standup
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-standup-to-quay
          context: architect
          image: "quay.io/giantswarm/standup"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build-standup
          filters:
            # Needed to trigger job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-standup-to-docker
          context: architect
          image: "docker.io/giantswarm/standup"
          username_envar: "DOCKER_USERNAME"
          password_envar: "DOCKER_PASSWORD"
          requires:
            - go-build-standup
          filters:
            # Needed to trigger job also on git tag.
            tags:
              only: /^v.*/
